name: Create a comment on new issues
on: 
  issues: 
    types: [opened]
jobs:
  comment-with-action: 
      runs-on: ubuntu-latest
      steps: 
         - name: "dumb github coontext"
           run: echo "hii"
           shell: bash
